name: Windows

on:
  push:
    branches:
      - main
      - decoupled-interval
  pull_request:

env:
  SCCACHE_GHA_ENABLED: "true"

jobs:
  build:

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows 2025 [Release]",
            os: windows-2025,
            build-type: "Release"
          }
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up MSVC environment
      uses: ilammy/msvc-dev-cmd@v1.13.0
      with:
        arch: x64

    - name: Set up sccache
      uses: mozilla-actions/sccache-action@v0.0.11
      with:
        version: "v0.18.0"

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      run: cmake ${{runner.workspace}}/utility -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER_LAUNCHER=sccache -DCMAKE_CXX_COMPILER_LAUNCHER=sccache -DWARNINGS_AS_ERRORS=ON

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --parallel --target everything

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: ctest --output-on-failure

    - name: Install Ariadne Utility
      working-directory: ${{runner.workspace}}/build
      run: cmake --install . --prefix "${{runner.workspace}}/install"
